export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const MERCHANTSERVICE_REPOSITORY = 'MERCHANTSERVICE_REPOSITORY';
export const PAYMENTMODE_REPOSITORY = 'PAYMENTMODE_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const WITHDRAWAL_REPOSITORY = 'WITHDRAWAL_REPOSITORY';
export const COUNTRY_REPOSITORY = 'COUNTRY_REPOSITORY';
